version: '3'
services:
  app:
    build: .
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=password"
    ports:
      - '8000:3000'
    volumes:
      - .:/usr/src/nerima_app
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local